name: Keep my-branch up to date

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required to allow merging

jobs:
  merge-main-into-mine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge main into de-valsplit
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: main
          to_branch: de-valsplit 

